//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMGBase64URLExtractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public long id { get; set; }
        public string source { get; set; }
        public string relativepart { get; set; }
        public bool visited { get; set; }
        public Nullable<int> sitioId { get; set; }
    }
}
