//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMGThief.GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long id { get; set; }
        public string email1 { get; set; }
    }
}
